#!/usr/bin/env python3
"""
Client for the Wazuh Server/Manager API (port 55000).

Provides:
  - get_token():            authenticate and return a JWT.
  - get_agent_id(name):     resolve an agent name to its ID (e.g. "victim" -> "001").
  - block_ip(ip, ...):      fire the 'firewall-drop' Active Response to block an IP.
  - unblock_ip(ip, ...):    fire the unblock Active Response (needs a custom AR in the lab).

Credentials via environment variables (do NOT hardcode, same as the indexer):
  WAZUH_API_USER  (default "wazuh")
  WAZUH_API_PASS  (no default — required)

Optional variables:
  WAZUH_API_HOST           (default "192.168.100.79")
  WAZUH_API_PORT           (default 55000)
  WAZUH_AR_COMMAND         (default "firewall-drop120" — must match the AR enabled in ar.conf)
  WAZUH_AR_UNBLOCK_COMMAND (default "firewall-allow0" — custom unblock AR, must exist in the lab)
  DRY_RUN                  ("1" = does not really execute, only simulates the call)
"""

import os
from base64 import b64encode

import requests
import urllib3

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

PROTOCOL = "https"
HOST = os.environ.get("WAZUH_API_HOST", "192.168.100.79")
PORT = int(os.environ.get("WAZUH_API_PORT", "55000"))
BASE_URL = f"{PROTOCOL}://{HOST}:{PORT}"

# Active Response command name and simulation mode.
# NOTE: the command name is the one in /var/ossec/etc/shared/ar.conf (generated by the
# Manager and pushed to the agent). It carries the TIMEOUT as a suffix: with
# <timeout>120</timeout> in the Manager's ossec.conf it becomes "firewall-drop120";
# with <timeout>no</timeout> it would be "firewall-drop0". It must match EXACTLY or the
# agent's execd rejects it with "(1311): Invalid command name".
AR_COMMAND = os.environ.get("WAZUH_AR_COMMAND", "firewall-drop120")

# Active Response command to UNblock. Wazuh has no API "delete": firewall-drop only
# self-removes when its <timeout> expires. A manual unblock needs a custom AR (e.g.
# 'firewall-allow') whose script runs `iptables -D`, configured in the lab like firewall-drop.
# The name must match ar.conf.
UNBLOCK_COMMAND = os.environ.get("WAZUH_AR_UNBLOCK_COMMAND", "firewall-allow0")

# Stronger active responses (custom ARs, configured in the lab like firewall-allow):
#   isolate-host : drop all traffic on the endpoint except the Wazuh Manager (EDR-style
#                  quarantine). unisolate-host reverts it. Both stateless -> suffix "0".
#   kill-process : kill a process on the endpoint by PID or name (passed as AR argument).
ISOLATE_COMMAND = os.environ.get("WAZUH_AR_ISOLATE_COMMAND", "isolate-host0")
UNISOLATE_COMMAND = os.environ.get("WAZUH_AR_UNISOLATE_COMMAND", "unisolate-host0")
KILL_COMMAND = os.environ.get("WAZUH_AR_KILL_COMMAND", "kill-process0")

DRY_RUN = os.environ.get("DRY_RUN", "0") == "1"


def get_token():
    """Authenticate against the Manager API and return the JWT."""
    user = os.environ.get("WAZUH_API_USER", "wazuh")
    password = os.environ.get("WAZUH_API_PASS")
    if not password:
        raise RuntimeError("WAZUH_API_PASS is missing from the environment.")

    basic = b64encode(f"{user}:{password}".encode()).decode()
    url = f"{BASE_URL}/security/user/authenticate"
    resp = requests.post(
        url,
        headers={"Authorization": f"Basic {basic}"},
        verify=False,
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()["data"]["token"]


def get_agent_id(agent_name, token=None):
    """Resolve an agent name to its numeric ID (e.g. 'victim' -> '001')."""
    token = token or get_token()
    url = f"{BASE_URL}/agents"
    resp = requests.get(
        url,
        headers={"Authorization": f"Bearer {token}"},
        params={"search": agent_name, "select": "id,name", "limit": 100},
        verify=False,
        timeout=10,
    )
    resp.raise_for_status()
    items = resp.json()["data"]["affected_items"]
    for item in items:
        if item.get("name") == agent_name:
            return item["id"]
    raise RuntimeError(f"No agent found with name '{agent_name}'.")


def list_agents(token=None):
    """
    Return the fleet status from the Manager API: a list of dicts with id, name,
    status (active/disconnected/never_connected/pending), version, lastKeepAlive and ip.
    Read-only — used by the fleet-health tool to judge whether telemetry is trustworthy.
    """
    token = token or get_token()
    url = f"{BASE_URL}/agents"
    resp = requests.get(
        url,
        headers={"Authorization": f"Bearer {token}"},
        params={"select": "id,name,status,version,lastKeepAlive,ip", "limit": 100,
                "sort": "id"},
        verify=False,
        timeout=10,
    )
    resp.raise_for_status()
    return resp.json()["data"]["affected_items"]


def _send_ar(command, ip=None, arguments=None, agent_name="victim", token=None):
    """
    Fire an Active Response `command` on agent `agent_name`. Shared core of every
    response tool (block/unblock/isolate/kill). Honors DRY_RUN.

    `ip`        -> passed to the AR script via alert.data.srcip (block/unblock).
    `arguments` -> passed as extra_args (kill-process target). Omit both for ARs that
                   need no target (isolate-host).

    Returns a dict with: ok (bool), dry_run (bool), agent_id, and the API detail.
    """
    token = token or get_token()
    agent_id = get_agent_id(agent_name, token)

    url = f"{BASE_URL}/active-response"
    body = {"command": command, "arguments": arguments or []}
    if ip is not None:
        # Wazuh passes the IP to the AR script through alert.data.srcip
        body["alert"] = {"data": {"srcip": ip}}

    if DRY_RUN:
        target = ip or (", ".join(arguments) if arguments else "the host")
        return {
            "ok": True,
            "dry_run": True,
            "agent_id": agent_id,
            "detail": f"[DRY-RUN] Not sent. Would run {command} against {target} on agent {agent_id}.",
        }

    resp = requests.put(
        url,
        headers={"Authorization": f"Bearer {token}", "Content-Type": "application/json"},
        params={"agents_list": agent_id},
        json=body,
        verify=False,
        timeout=15,
    )

    try:
        detail = resp.json()
    except ValueError:
        detail = resp.text

    return {
        "ok": resp.status_code in (200, 201),
        "dry_run": False,
        "agent_id": agent_id,
        "status_code": resp.status_code,
        "detail": detail,
    }


def block_ip(ip, agent_name="victim", reason="", token=None):
    """Fire the block AR (AR_COMMAND, 'firewall-drop') against `ip`."""
    return _send_ar(AR_COMMAND, ip, agent_name=agent_name, token=token)


def unblock_ip(ip, agent_name="victim", reason="", token=None):
    """
    Fire the UNblock AR (UNBLOCK_COMMAND, 'firewall-allow') against `ip`.
    Requires that AR to be configured in the lab (see UNBLOCK_COMMAND).
    """
    return _send_ar(UNBLOCK_COMMAND, ip, agent_name=agent_name, token=token)


def isolate_host(agent_name="victim", reason="", token=None):
    """Quarantine the endpoint: fire ISOLATE_COMMAND ('isolate-host'). No target needed."""
    return _send_ar(ISOLATE_COMMAND, agent_name=agent_name, token=token)


def unisolate_host(agent_name="victim", reason="", token=None):
    """Lift the quarantine: fire UNISOLATE_COMMAND ('unisolate-host')."""
    return _send_ar(UNISOLATE_COMMAND, agent_name=agent_name, token=token)


def kill_process(target, agent_name="victim", reason="", token=None):
    """
    Kill a process on the endpoint. `target` is a PID or a process name, passed to the
    AR script as an argument (KILL_COMMAND, 'kill-process').
    """
    return _send_ar(KILL_COMMAND, arguments=[str(target)], agent_name=agent_name, token=token)


if __name__ == "__main__":
    # Manual use: print a token (compatibility with the original script).
    print("\nLogin request ...\n")
    print(get_token())
